# Generated by Django 2.1 on 2018-08-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20180811_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votinghistory',
            name='vote_type',
            field=models.IntegerField(),
        ),
    ]
